global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: true
  footprint: [ [-0.1,-0.15], [0.425,-0.15], [0.425,0.15], [-0.1,0.15] ]
  robot_radius: 0.2
  footprint_padding: 0.2
 
  transform_tolerance: 0.1
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}




