## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_x_min: -275
accel_x_max: 284
accel_y_min: -284
accel_y_max: 280
accel_z_min: -308
accel_z_max: 207

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [180.164, 74.3922, 68.5088]
magn_ellipsoid_transform: [[0.892735, -0.0107427, -0.0339768], [-0.0107427, 0.888744, -0.00215294], [-0.0339768, -0.00215294, 0.989223]]

# AHRS to robot calibration
imu_yaw_calibration: 0

### gyroscope
gyro_average_offset_x: -26.77
gyro_average_offset_y: -16.23
gyro_average_offset_z: -7.30
